spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

#cloud:
#  gateway:
#    discovery:
#      locator:
#        enabled: true
#    routes:
#      - id: LOGIN-SERVICE
#        uri: lb://login-service
#        predicates:
#          - Path=/api/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

